popolee/account/urls.py
from django.urls import path
from . import views
from .api_views import *
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('login',views.login_page,name="login_page"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register',views.register_page,name="register_page"),
    path('my_page/<int:pk>',views.my_page,name="my_page"),

    #api
    #path('api/auth/regist', Api_regist.as_view(), name='api_regist'),
    #path('api/auth/login', Api_login.as_view(), name='api_login'),
    #path('api/auth/logout', Api_logout.as_view(), name='api_logout'),
    #path('api/view/feed', Api_feed.as_view(), name='api_feed'),
]

popolee/feed/urls.py
from django.urls import path,include
from . import views
from .api_views import *
from django.contrib.auth import views as auth_views

app_name = 'feed'

urlpatterns = [
    #For First Page & Login
    path('',views.main_page,name="main_page"),
    path('upload/',views.upload_page,name="upload_page"),
    path('post/<int:pk>',views.post_page,name="post_page"),

    #api
    path('api/view/feed', Api_feed.as_view(), name='api_feed'),
    
]

popolee/popolee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include('feed.urls')),
    path("account/", include('account.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

popolee/feed/models.py
from django.db import models
from account.models import Profile

class Post(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name= "publisher")
    image = models.ImageField(upload_to='images', blank=False)
    likecount = models.IntegerField(default = 0)
    headcount = models.IntegerField(default = 0)
    malecount = models.IntegerField(default = 0)
    femalecount = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add=True)

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name= "likes")
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name= "likes")
    
    class Meta:
        unique_together = ('post', 'profile')

popolee/feed/views.py
from django.http import HttpResponse
from .models import *
from django.shortcuts import render, redirect
from django.contrib import auth
from django.middleware.csrf import CsrfViewMiddleware
from datetime import datetime

def post_page(request, pk):
    print(request)
    context = {}

    #check user
    requester_profile = None
    if request.user.is_authenticated == True:
        check_profile = Profile.objects.filter(user=request.user).first()
        if check_profile:
            requester_profile = check_profile
    context["requester_profile"] = requester_profile

    #show post
    post = Post.objects.filter(pk=pk).first()
    context['post'] = post

    #check publisher and requester
    if post.profile == requester_profile:
        user_is_publisher = True
    else:
        user_is_publisher = False
    context["user_is_publisher"] = user_is_publisher

    
    if request.method == "POST":
        print(request.POST)

        #feat : delete the post
        if "del" in request.POST:
            post.delete()
            return redirect("feed:main_page")
            
        
        #feat : like btn
        if "likebtn" in request.POST:
            #Anonymous user -> login to like
            if requester_profile == None:
                return redirect('account:login_page')
            else:
                #check Like status (search in Like DB)
                like_info = Like.objects.filter(post=post, profile = requester_profile).first()
                
                #like cancel
                if like_info:
                    post.likecount -= 1
                    post.save()
                    like_info.delete()

                #like confirm
                else:
                    post.likecount += 1
                    post.save()
                    Like.objects.create(post = post, profile = requester_profile)


    return render(request, 'post_page.html' ,context)

def upload_page(request):
    print(request)
    context = {}

    #check user
    requester_profile = None
    if request.user.is_authenticated == True:
        check_profile = Profile.objects.filter(user=request.user).first()
        if check_profile:
            requester_profile = check_profile
    context["requester_profile"] = requester_profile

    #Anonymous user -> login
    if requester_profile == None:
        return redirect('account:login_page')
    
    
    if request.method == "POST":
        print(request.POST)
        print(request.FILES)
        print("####")

        #upload img file (create Post model record)
        if request.FILES.get("upload_img"):
            Post.objects.create(profile = requester_profile, image = request.FILES.get("upload_img"))
            return redirect("feed:main_page")

    
    return render(request, 'upload_page.html',context)

def main_page(request):
    print(request)
    context = {}

    #check user
    requester_profile = None
    if request.user.is_authenticated == True:
        check_profile = Profile.objects.filter(user=request.user).first()
        if check_profile:
            requester_profile = check_profile
    context["requester_profile"] = requester_profile


    #show feed(default)
    max_images = 10     
    posts = Post.objects.order_by('-likecount')[:max_images]


    if request.method == "POST":
        print(request.POST)

        #feat : sort options
        sortoption = request.POST.get("sortoption")
        match sortoption:
            case 'most_like':
                sort_field = '-likecount'
            case 'show_old':
                sort_field = 'created_at'
            case 'show_new':
                sort_field = '-created_at'

        #feat : tag options(headcount)
        tag = request.POST.get("headcount")

        if tag != '':
            posts = Post.objects.filter(headcount = tag).order_by(sort_field)[:max_images]  
        else:
            posts = Post.objects.order_by(sort_field)[:max_images]

    context["posts"] = posts

    return render(request, 'main_page.html',context)

popolee/feed/templates/main_page.html
<!DOCTYPE html>
<html>
<head>
    <title>이미지 피드</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>포포리 피드</h1>
    <h2>You : {{requester_profile}}</h2>

    {% if not requester_profile %}
    {% else %}
        <form method="get" action="{% url 'account:my_page' requester_profile.id %}">
            <div class="button-container">
                <button type="submit" name="my_page" class="btn">개인페이지</button>
            </div>
        </form>
    {% endif %}

    <form method="get" action="{% url 'feed:upload_page' %}">
        <div class="button-container">
            <button type="submit" class="btn">업로드</button>
        </div>
    </form>

    <form method = "post" >
        {% csrf_token %}
        <div class="drop-container"> 
            <select class="dropmenu" name="sortoption" id="sortoption" onchange="updatePlaceholder()">
                <option value="most_like" selected>like</option>
                <option value="show_old">old</option>
                <option value="show_new">new</option>
            </select>
            <div class="input-box">
                <input type="number" name="headcount" id="headcount" placeholder="headcount">
                <input type="number" name="in_male" id="in_male" placeholder="Male">
                <input type="number" name="in_female" id="in_female" placeholder="Female">
            </div>
        </div>
        

        <div class="button-container">
            <button type="submit" name="search" class="btn">검색</button>
        </div>
    </form>

    {% for post in posts %}
        <div class="card">
            <p><strong>업로드한 유저:</strong> {{ post.profile.nickname }}</p>
            <p><strong>업로드 시간:</strong> {{ post.created_at }}</p>
            <p><strong>pk:</strong> {{ post.pk }}</p>

            {% if post.image %}
                <a href="./post/{{post.pk}}">
                    <img src="{{ post.image.url }}" alt="이미지">
                </a>    
            {% else %}
                <p>[이미지 없음]</p>
            {% endif %}

            <p><strong>좋아요:</strong> {{ post.likecount }}</p>
            <p><strong>전체 인원:</strong> {{ post.headcount }}</p>
            <p><strong>남성:</strong> {{ post.malecount }} / 여성: {{ post.femalecount }}</p>
        </div>
    {% empty %}
        <p>이미지가 없습니다.</p>
    {% endfor %}
</body>
</html>
<script>
    function updatePlaceholder() {
        const option = document.getElementById("sortoption").value;
        // 옵션에 따라 placeholder 변경 등 로직 구현
    }
</script>

popolee/feed/templates/post_page.html
<!DOCTYPE html>
<html>
<head>
    <title>이미지 피드</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>포포리 : post_page</h1>
    <h2>{{requester_profile.username}}</h2>
    

    <div class="card">
        <p><strong>업로드한 유저:</strong> {{ post.profile.nickname }}</p>

        <form method="get" action="{% url 'account:my_page' post.profile.id %}">
            <div class="button-container">
                <button type="submit" class="btn">{{post.profile.nickname}}의 페이지</button>
            </div>
        </form>

        <p><strong>업로드 시간:</strong> {{ post.created_at }}</p>
        <p><strong>pk:</strong> {{ post.pk }}</p>

        {% if post.image %}
                <img src="{{ post.image.url }}" alt="이미지">
        {% else %}
            <p>[이미지 없음]</p>
        {% endif %}

        <p><strong>좋아요:</strong> {{ post.likecount }}</p>
        <form method="post">
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" name="likebtn" class="btn">좋아요</button>
            </div>
        </form>

        <p><strong>전체 인원:</strong> {{ post.headcount }}</p>
        <p><strong>남성:</strong> {{ post.malecount }} / 여성: {{ post.femalecount }}</p>

        {% if user_is_publisher %}
            <form method="post" id="delete-form">
                {% csrf_token %}
                <div class="button-container">
                    <button type="submit" name="del" class="btn">게시글 삭제</button>
                </div>
            </form>
        {% else %}
        {% endif %}

        

        
    </div>
</body>

<script>
    const form = document.getElementById('delete-form');
    form.addEventListener('submit', function (e) {
      if (!confirm('정말 삭제하시겠습니까?')) {
        e.preventDefault(); // 제출 막기
      }
    });
  </script>
</html>

popolee/feed/templates/upload_page.html
<!DOCTYPE html>
<html>
<head>
    <title>업로드 피드</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>업로드</h1>
    <h2>You : {{requester_profile}}</h2>

    <div class="container">
        <div class="image-upload" id="image-upload">

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="button">
                    <label for="chooseFile">
                        👉 CLICK HERE! 👈
                    </label>
                </div>
                <input type="file" id="upload_img" name="upload_img" accept="image/*" onchange="loadFile(this)">
                <div class="button-container">
                    <button type="submit" name="search" class="btn">업로드 하기</button>
                </div>
            </form>

        </div>
        
    </div>

    
</body>
</html>
<script>
    function updatePlaceholder() {
        const option = document.getElementById("sortoption").value;
        // 옵션에 따라 placeholder 변경 등 로직 구현
    }
</script>