popolee/account/urls.py
from django.urls import path
from . import views
from .api_views import *
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    path('login',views.login_page,name="login_page"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register',views.register_page,name="register_page"),
    path('my_page/<int:pk>',views.my_page,name="my_page"),

    #api
    #path('api/auth/regist', Api_regist.as_view(), name='api_regist'),
    #path('api/auth/login', Api_login.as_view(), name='api_login'),
    #path('api/auth/logout', Api_logout.as_view(), name='api_logout'),
    #path('api/view/feed', Api_feed.as_view(), name='api_feed'),
]

popolee/feed/urls.py
from django.urls import path,include
from . import views
from .api_views import *
from django.contrib.auth import views as auth_views

app_name = 'feed'

urlpatterns = [
    #For First Page & Login
    path('',views.main_page,name="main_page"),
    path('upload/',views.upload_page,name="upload_page"),
    path('post/<int:pk>',views.post_page,name="post_page"),

    #api
    path('api/view/feed', Api_feed.as_view(), name='api_feed'),
    
]

popolee/popolee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include('feed.urls')),
    path("account/", include('account.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

popolee/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver


class User(AbstractUser):
    username = models.EmailField('email address', unique=True)
    # email 필드 삭제 또는 사용하지 않음

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    nickname = models.CharField(max_length=30, unique=True)
    profile_image = models.ImageField(upload_to='profile', blank=False)

    def __str__(self) -> str:
        return self.nickname

popolee/account/views.py
from .models import *
from feed.models import *
from django.shortcuts import render, redirect
from django.contrib import auth
from django.middleware.csrf import CsrfViewMiddleware
from datetime import datetime

# Create your views here.
def my_page(request, pk):
    print(request)
    context = {}

    #check user
    requester_profile = None
    if request.user.is_authenticated == True:
        check_profile = Profile.objects.filter(user=request.user).first()
        if check_profile:
            requester_profile = check_profile
    context["requester_profile"] = requester_profile

    #get page_owner
    page_owner = Profile.objects.filter(id = pk).first()
    print(page_owner)

    #show posts
    posts = Post.objects.filter(profile = page_owner).order_by('-likecount')

    if request.method == "POST":
        print(request.POST)

        #feat : sort options
        sortoption = request.POST.get("sortoption")
        match sortoption:
            case 'most_like':
                sort_field = '-likecount'
            case 'show_old':
                sort_field = 'created_at'
            case 'show_new':
                sort_field = '-created_at'
        posts = Post.objects.filter(profile = page_owner).order_by(sort_field)
    
    context['posts'] = posts

    return render(request, 'my_page.html', context)

def login_page(request):
    print(request)
    context = {}

    err_state = False

    if request.method == "POST":
        userid = request.POST.get("id")
        pwd = request.POST.get("pwd")

        #find user with userid and pwd
        user = auth.authenticate(request, username = userid, password = pwd)

        if user is not None:
            auth.login(request, user)
            return redirect('feed:main_page')
        #login fail
        else:
            err_state = True

    context["err_state"] = err_state
    context["err"] = "Wrong id or password, Try again"

    return render(request, 'login_page.html', context)


from django import forms
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

def register_page(request):
    print("this is register_page")
    print(request)
    context = {}

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save()
            print(user.username)
            Profile.objects.create(user=user, nickname = user.username)
            return redirect('account:login_page')  # 회원가입 후 로그인 페이지 등으로 리디렉션
    else:
        form = CustomUserCreationForm()
    return render(request, 'register_page.html', {'form': form})

popolee/account/templates/login_page.html
<!DOCTYPE html>
<html>
<head>
    <title>로그인 피드</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>로그인</h1>

    <form method = "post" >
        {% csrf_token %}
        <div class="input-box">
            <input type="text" name="id" id="id" placeholder="ID">
        </div>
        <div class="input-box">
            <input type="text" name="pwd" id="pwd" placeholder="Password">
        </div>

        <div class="button-container">
            <button type="submit" name="login" class="btn">로그인</button>
        </div>
    </form>

    {% if err_state %}
        <p>{{err}}</p>
    {% else %}
    {% endif %}


    <form method="get" action="{% url 'account:register_page' %}">
        <div class="button-container">
            <button type="submit" class="btn">회원가입</button>
        </div>
    </form>
    
</body>
</html>
<script>
    function updatePlaceholder() {
        const option = document.getElementById("sortoption").value;
        // 옵션에 따라 placeholder 변경 등 로직 구현
    }
</script>

popolee/account/templates/my_page.html
<!DOCTYPE html>
<html>
<head>
    <title>개인페이지</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>포포리 : my_page</h1>
    <h2>{{user.username}}</h2>

    <form method="post" action="{% url 'account:logout' %}">
        {% csrf_token %}

        <div class="button-container">
            <button type="submit" class="btn">로그아웃</button>
        </div>
    </form>

    <form method="get" action="{% url 'feed:upload_page' %}">
        <div class="button-container">
            <button type="submit" class="btn">업로드</button>
        </div>
    </form>

    <form method = "post" >
        {% csrf_token %}
        <div class="drop-container"> 
            <select class="dropmenu" name="sortoption" id="sortoption" onchange="this.form.submit()">
                <option value="most_like" selected>like</option>
                <option value="show_old">old</option>
                <option value="show_new">new</option>
            </select>
        </div>
    </form>

    {% for post in posts %}
        <div class="card">
            <p><strong>업로드한 유저:</strong> {{ post.profile.nickname }}</p>
            <p><strong>업로드 시간:</strong> {{ post.created_at }}</p>
            <p><strong>pk:</strong> {{ post.pk }}</p>

            {% if post.image %}
                <a href="{% url 'feed:post_page' post.pk %}">
                    <img src="{{ post.image.url }}" alt="이미지">
                </a>    
            {% else %}
                <p>[이미지 없음]</p>
            {% endif %}

            <p><strong>좋아요:</strong> {{ post.likecount }}</p>
            <p><strong>전체 인원:</strong> {{ post.headcount }}</p>
            <p><strong>남성:</strong> {{ post.malecount }} / 여성: {{ post.femalecount }}</p>
        </div>
    {% empty %}
        <p>이미지가 없습니다.</p>
    {% endfor %}
</body>
</html>

popolee/account/templates/register_page.html
<!DOCTYPE html>
<html>
<head>
    <title>로그인 피드</title>
    <style>
        img {
            max-width: 300px;
            border-radius: 8px;
        }
        .card {
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h2>회원가입</h2>

    <form method="post">
        {% csrf_token %}
            {{ form.as_p }}

            {% if form.errors %}
                <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                    <li style="color: red;">{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li style="color: red;">{{ error }}</li>
                {% endfor %}
                </ul>
            {% endif %}

        <button type="submit">회원가입</button>
    </form>


    
</body>
</html>
<script>
    function updatePlaceholder() {
        const option = document.getElementById("sortoption").value;
        // 옵션에 따라 placeholder 변경 등 로직 구현
    }
</script>